services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pwddamdev
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: UTC
    networks:
      - damiotdevnet
    volumes:
      - timescaledb_data:/var/lib/postgresql/data 
    
volumes:
  timescaledb_data: